config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  namespace :games, path: '/' do
    get :new
    get :play, to: :new
    post :play
    post :random
    post :start
  end

  root to: redirect('/new')
  get '*path', to: redirect('/new')
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/game.rb
class Game
  attr :generation, :grid, :cols, :rows, :over

  MAX = 50

  def initialize(params)
    if params.try :[], :random
      randomize
    else
      @generation = params.generation.to_i
      @rows = params.rows.to_i
      @rows = MAX if rows > MAX
      @cols = params.cols.to_i
      @cols = MAX if cols > MAX

      if params.try :grid
        @grid = params.grid
      else
        @grid = load_grid
        fill params.cells if params.try :cells
      end
    end
  end

  def randomize
    @generation = 0
    @rows = @cols = rand 10..50
    @grid = load_random_grid
  end

  def next_generation
    new_grid = load_grid
    grid.each_with_index do |row, y|
      row.each_with_index do |col, x|
        count = neighbors_count(y, x)
        new_grid[y][x] = begin
          if col.zero?
            count == 3 ? 1 : 0
          else
            count.in?([2, 3]) ? 1 : 0
          end
        end
      end
    end
    @over = true if new_grid == grid
    @grid = new_grid
    @generation += 1
  end

  private

  def load_grid
    Array.new(rows) { Array.new(cols, 0) }
  end

  def load_random_grid
    Array.new(rows) do
      Array.new(cols) do
        case rand(1..100)
        when 1..80 then 0
        else 1
        end
      end
    end
  end

  def fill(cells)
    cells.each_with_index do |row, y|
      row.each_with_index do |col, x|
        grid[y][x] = 1 if col == 1
      end
    end
  end

  def neighbors_count(y, x)
    neighbors(y, x).count { |col| col == 1 }
  end

  def neighbors(y, x)
    (-1..1).each_with_object [] do |py, values|
      (-1..1).each do |px|
        next if py.zero? && px.zero?

        i = y + py
        j = x + px
        i = 0 unless i < rows
        j = 0 unless j < cols
        values << grid[i][j]
      end
    end
  end
end

app/models/upload.rb
class Upload
  include ActiveModel::Validations

  attr :file, :generation, :rows, :cols, :cells

  def initialize(file)
    @file = file
    parse_file
  end

  def parse_file
    @cells = []
    File.open(file) do |f|
      f.each_with_index do |line, i|
        case i
        when 0
          @generation = line.match(/\d+:/).to_s.scan(/\d+/).first
        when 1
          @rows, @cols = line.scan(/\d+/)
        else
          row = line.scan(/./).map { |s| s == '*' ? 1 : 0 }
          @cells << row unless row.empty?
        end
      end
    end
  rescue StandardError
    nil
  end

  validates_presence_of :file
  validates_size_of :file, maximum: 1.megabyte, message: 'Must not exceed 1MB'
  validate do
    generation or errors.add :file, 'Missing generation number'
    (rows and cols) or errors.add :file, 'Missing grid size'
    cells.present? or errors.add :file, 'Missing population state'
  end
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :registerable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  before_action :authenticate_user!

  rescue_from ActionController::ParameterMissing do
    redirect_to games_new_url
  end

  layout 'game'

  def play
    upload = Upload.new file_params

    if upload.valid?
      @game = Game.new upload
    else
      redirect_to games_new_url, alert: upload.errors
    end
  end

  def random
    @game = Game.new random: true

    render :play
  end

  def start
    game = Game.new game_params
    game.next_generation

    html = ApplicationController.render partial: 'games/grid', locals: { game: game }
    render json: { game: game, grid: html }
  end

  private

  def file_params
    params.require(:file)
  end

  def game_params
    JSON.parse params.require(:game), object_class: OpenStruct
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def inside_layout(layout, &block)
    render layout: "layouts/#{layout}", inline: capture(&block)
  end
end

app/views/application/_alerts.slim
#alert
  - alert.try :each do |name, msg|
    p
      b #{name.capitalize} errors:
      - msg.each do |m|
       br
       = m

  = alert if alert.is_a? String

app/views/games/_grid.slim
- game ||= @game

p
  ' Generation:
  = game.generation

table: tbody
  - game.rows.times do |y|
    tr
      - game.cols.times do |x|
        - row = game.grid[y]
        - cell = row.try :[], x
        td class="#{:live if cell == 1}"

app/views/games/new.slim
p Choose a file to start a new game

details
  summary File example
  pre
    code
      |
        Generation 1:
        Grid: 5 8
        ........
        ..*.....
        ..*..*..
        ..***...
        ........

p
  #or OR
  = form_with url: "random" do |f|
    = hidden_field_tag :authenticity_token, form_authenticity_token
    = f.button "PLAY RANDOM", class: :outline

= form_with url: "play", multipart: true do |f|
  = f.file_field :file, accept: "text/plain", required: true
  = hidden_field_tag :authenticity_token, form_authenticity_token
  = f.submit "PLAY FILE"

app/views/games/play.slim
#game
  = render "grid"

= form_with url: "start", local: false do |f|
  = f.hidden_field :game, id: :game_json, value: @game.to_json
  = f.button :START, id: :start, type: :button
  = f.button :STOP, id: :stop, type: :button, hidden: true

small
  h4#gameover GAME OVER
  p#or OR
  = link_to "NEW GAME", games_new_path, id: :new_game

app/views/layouts/application.slim
doctype html
html
  head
    title Game of Life
    = csrf_meta_tags
    = csp_meta_tag
    meta content="width=device-width,initial-scale=1" name="viewport"
    = favicon_link_tag
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_pack_tag 'application', 'data-turbolinks-track': 'reload'
  body
    = yield

app/views/layouts/game.slim
= inside_layout "application" do
  .game
    h1 GAME OF LIFE
    = yield
    = render "alerts"

  footer
    = link_to "QUIT", destroy_user_session_path, method: :delete
    .credits = link_to '© FraV8', 'https://gitlab.com/FraV8', target: :blank